# Site settings
title: Rebecca's Profile
email: rebecca@lavidabento.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages-24"
url: "http://beckyloops.github.io"
twitter_username: lopezkriss
github_username:  beckyloops
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
